In [1]:
print("hello class")

hello class


In [2]:
weight_kg  = 55

In [3]:
print(weight_kg)

55


In [6]:
print("weight in 'pounds':", 2.2 * weight_kg)

weight in 'pounds': 121.00000000000001


In [7]:
weight_kg = 57.5

In [8]:
print("weight in kg is now:", weight_kg)

weight in kg is now: 57.5


In [11]:
weight_lb = 2.2 * weight_kg
print('weight in kilograms:', weight_kg, 'and in pounds:', weight_lb)

weight in kilograms: 57.5 and in pounds: 126.50000000000001


In [14]:
weight_kg  = 100.0
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)

weight in kilograms is now: 100.0 and weight in pounds is still: 126.50000000000001


In [15]:
%whos

Variable    Type      Data/Info
-------------------------------
autopep8    module    <module 'autopep8' from '<...>te-packages/autopep8.py'>
json        module    <module 'json' from '/Use<...>hon3.6/json/__init__.py'>
weight_kg   float     100.0
weight_lb   float     126.50000000000001


In [16]:
import numpy as np

In [18]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter = ',')

In [19]:
data

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [20]:
print(type(data))

<class 'numpy.ndarray'>


In [21]:
data.dtype

dtype('float64')

In [22]:
def my_func():
    print("hello")

In [24]:
my_func

<function __main__.my_func>

In [31]:
data.shape

(60, 40)

In [32]:
data[0,0]

0.0

In [34]:
print("middle value in array:",data[30,20])

middle value in array: 13.0


In [36]:
data[0,0]

0.0

In [38]:
data[0:4, 0:10]

array([[ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.],
       [ 0.,  1.,  2.,  1.,  2.,  1.,  3.,  2.,  2.,  6.],
       [ 0.,  1.,  1.,  3.,  3.,  2.,  6.,  2.,  5.,  9.],
       [ 0.,  0.,  2.,  0.,  4.,  2.,  2.,  1.,  6.,  7.]])

In [39]:
data[4,0:10]

array([ 0.,  1.,  1.,  3.,  3.,  1.,  3.,  5.,  2.,  4.])

In [40]:
element = 'oxygen'
print('the first three characters:', element[0:3])
print('the last three characters:', element[3:6])

the first three characters: oxy
the last three characters: gen


In [41]:
element[4:]

'en'

In [45]:
doubled_data = data * 2.0
data

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [44]:
doubled_data

array([[ 0.,  0.,  2., ...,  6.,  0.,  0.],
       [ 0.,  2.,  4., ...,  2.,  0.,  2.],
       [ 0.,  2.,  2., ...,  4.,  2.,  2.],
       ..., 
       [ 0.,  2.,  2., ...,  2.,  2.,  2.],
       [ 0.,  0.,  0., ...,  0.,  4.,  0.],
       [ 0.,  0.,  2., ...,  2.,  2.,  0.]])

In [46]:
tripled_data = doubled_data + data

In [47]:
tripled_data

array([[ 0.,  0.,  3., ...,  9.,  0.,  0.],
       [ 0.,  3.,  6., ...,  3.,  0.,  3.],
       [ 0.,  3.,  3., ...,  6.,  3.,  3.],
       ..., 
       [ 0.,  3.,  3., ...,  3.,  3.,  3.],
       [ 0.,  0.,  0., ...,  0.,  6.,  0.],
       [ 0.,  0.,  3., ...,  3.,  3.,  0.]])

In [52]:
print(np.mean(data, axis = 1))

IndexError: tuple index out of range

In [49]:
data.mean()

6.1487499999999997

In [58]:
patient_max = np.max(data, axis = 1)
np.max(data, axis = 1).shape

(60,)

In [55]:
patient_max.shape

(60,)

In [56]:
data.shape

(60, 40)

In [ ]:
np.mean(data, axis = )